version: 2
jobs:
  one:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/spring-fortune

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m


    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 10

  two:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/spring-fortune

    steps:
      - checkout

      - restore_cache:
          key: spring-fortune-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
           - ~/.m2
          key: spring-fortune-{{ checksum "pom.xml" }}

      - run:
          name: Start SauceLabs Tunnel (required if testing on CircleCI container)
          command: |
            curl https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            cd sc-*
            # startup saucelabs tunnel as background task (its a blocking command)
            bin/sc -u ${SAUCELABS_USER} -k ${SAUCELABS_KEY} &
            #wait for sauce tunnel up to 1 minute
            wget --retry-connrefused --no-check-certificate -T 60 localhost:4445

      - run:
          name: Run tests
          command: mvn package -B


workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one