version: 2
jobs:
  one:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/spring-fortune

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m


    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 10

  two:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/spring-fortune

    steps:
      - checkout

      - restore_cache:
          key: spring-fortune-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
           - ~/.m2
          key: spring-fortune-{{ checksum "pom.xml" }}

      - run:
          name: Run tests
          command: mvn package -B


workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one