version: 2
jobs:
  one:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 10

  two:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one